[build]
builder = "Nixpacks"

[deploy]
startCommand = "cd backend && python manage.py db upgrade && python manage.py run"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
id = "backend"
source = "backend/"